# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: YOUR_SECRET_KEY_BASE
  tmp_dir: /Full/Path/To/Dir/For/Temp/Files
  blender_path: /Full/Path/To/Blender/Executable
  blender_dummy_path: /Full/Path/To/Dummy/Blender/File
  dae_to_json_path: /Full/Path/To/dae_to_json.py
  aws_access_key_id: YOUR_AWS_ACCESS_KEY_ID
  aws_secret_access_key: YOUR_AWS_SECRET_ACCESS_KEY
  aws_region: YOUR_AWS_REGION
  aws_bucket: YOUR_AWS_BUCKET_NAME

test:
  secret_key_base: fdbb87a801ea1e4a5e8ae008d5dacf255d576ad47f026bddb443944f80b1c064d30737792a21c7166a3303b530e6bae4e2e6eda6b2c956af7b23cc7c580b83d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
